ingress-nginx:
  controller:
    # -- Use a `DaemonSet` or `Deployment`
    kind: DaemonSet

    service:
      ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
      externalTrafficPolicy: "Local"
      loadBalancerIP: "128.140.26.162"
      nodePorts:
        http: 30080
        https: 30443

    # -- Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "true"

    metrics:
      port: 10254
      # if this port is changed, change healthz-port: in extraArgs: accordingly
      enabled: true

      serviceMonitor:
        enabled: true