apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-workload-devops

spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: demo-argo-ui

  source:
    path: ingress-nginx/nginx-workload
    repoURL: https://github.com/hubtech-trungnt/helm-chart.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background