apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus

spec:
  destination:
    namespace: monitor
    server: https://kubernetes.default.svc
  project: demo-argo-ui

  source:
    path: monitor/prometheus-stack
    repoURL: https://github.com/hubtech-trungnt/helm-chart.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background
    - CreateNamespace=true