apiVersion: v2
version: 1.0.0
name: kube-prometheus-stack
dependencies:
  - name: kube-prometheus-stack
    version: 48.3.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: metrics-server
    version: 3.10.0
    repository: https://kubernetes-sigs.github.io/metrics-server
