apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd

spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: demo-argo-ui
  source:
    path: argocd/argocd
    repoURL: https://github.com/hubtech-trungnt/helm-chart.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background