apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager

spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc

  source:
    path: cert-manager/cert-manager
    repoURL: https://github.com/hubtech-trungnt/helm-chart.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background