apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-argo-ui
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: demo argo CD by UI
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/hubtech-trungnt/helm-chart.git
