deploychart:
  # Default values for helm-template.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 1

  kind: Deployment

  fullnameOverride: demo-nginx

  image:
    repository: nginx
    tag: stable-alpine3.17
    containerPort: 80
    containerPortName: http

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: devops.chancode.click
        paths:
        - path: /
          pathType: Prefix
    tls:
      - secretName: devops-demo-tls
        hosts:
          - devops.chancode.click
