agro-cd:  
  redis-ha:
    enabled: true

  controller:
    replicas: 2

  server:
    autoscaling:
      enabled: true
      minReplicas: 2

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2

  applicationSet:
    replicas: 1